<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>mazesurvivor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="com.IvanMurzak.ReflectorNet" Version="5.4.0" />
    <PackageReference Include="com.IvanMurzak.McpPlugin" Version="7.5.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="addons/godot_mcp/extensions.catalog.json" LogicalName="Godot-MCP.extensions.catalog.json" />
  </ItemGroup>
</Project>